INSERT INTO DEPOSITOR (ID, BALANCE) VALUES (10, 1000);
INSERT INTO DEPOSITOR (ID, BALANCE) VALUES (1, 1000);
INSERT INTO DEPOSITOR (ID, BALANCE) VALUES (2, 2000);
INSERT INTO DEPOSITOR (ID, BALANCE) VALUES (3, 3000);

--INSERT INTO OPERATION (ID, DEPOSITOR_DONOR_ID, DEPOSITOR_ACCEPTOR_ID,
--                      OPERATION_TYPE INT, CHANGE_BALANCE NUMERIC, operation_date timestamp)
--                      VALUES (1, 1, 1, 1, 500, '2024-01-20T12:00:00.000');